#!/usr/bin/env node

import { execSync } from 'child_process';

try {
  // Get the list of staged files
  const stagedFiles = execSync('git diff --cached --name-only', {
    encoding: 'utf8',
  });

  // Check if any files in dist/ are staged
  const distFiles = stagedFiles
    .split('\n')
    .filter(file => file.trim() && file.startsWith('dist/'));

  // Filter out manually created export files that are allowed to be committed
  const allowedDistFiles = ['dist/index.js', 'dist/index.d.ts'];
  const forbiddenDistFiles = distFiles.filter(
    file => !allowedDistFiles.includes(file)
  );

  if (forbiddenDistFiles.length > 0) {
    console.error(
      '❌ Error: Cannot commit changes to auto-generated files in dist/ folder!'
    );
    console.error('');
    console.error(
      'The following auto-generated files in dist/ are staged for commit:'
    );
    forbiddenDistFiles.forEach(file => console.error(`  - ${file}`));
    console.error('');
    console.error(
      'These files are generated by CI and should not be manually edited.'
    );
    console.error('Please remove these files from staging:');
    console.error(`  git reset HEAD ${forbiddenDistFiles.join(' ')}`);
    console.error('');
    console.error(
      'Note: dist/index.js and dist/index.d.ts are manually created export files and can be committed.'
    );
    console.error(
      'If you need to update other generated files, please do so through CI/CD pipeline.'
    );
    process.exit(1);
  }

  if (distFiles.length > 0) {
    console.log(
      '✅ Allowed dist/ files detected (index.js, index.d.ts). Proceeding with commit...'
    );
  } else {
    console.log(
      '✅ No dist/ folder changes detected. Proceeding with commit...'
    );
  }
} catch (error) {
  console.error('Error checking dist folder:', error.message);
  process.exit(1);
}
